### ISSUE TITLE
Apply `as const` to objects?

### ISSUE THREAD

**Issue by mcmire** [MetaMask/metamask-eth-abis#5]
I mentioned this in a [`controllers` PR](https://github.com/MetaMask/controllers/pull/667#discussion_r780427373), but I believe that in order to provide proper type safety, each object should have `as const` on it. That is to say:

``` typescript
export const abiERC1155 = [
  ...
] as const;
```

Why? Say you have a function or method and you want to ensure that it must take an ERC-1155 ABI. You might think you can say:

``` typescript
import { abiERC1155 } from "@metamask/metamask-eth-abis";

function foo(abi: typeof abiERC1155) {
  // ...
}
```

But this won't do what you think it will, because the type of the ABI object doesn't verify that you've passed an ERC-1155 ABI exactly, just something that matches the shape.

Let's simplify this:

``` typescript
const value = {
  foo: "bar",
  baz: "qux",
};
```

The inferred type of this is:

``` typescript
{
  foo: string;
  baz: string;
}
```

That means that if you have a function `foo(x: typeof value)`, this function will allow `foo({ foo: "xxxxx", bar: "yyyyyy" })`. Probably not what you want.

But if you add `as const` you can harden this. The inferred type of:

``` typescript
const value = {
  foo: "bar",
  baz: "qux",
} as const;
```

is:

``` typescript
{
  foo: "bar";
  baz: "qux";
}
```

So now `foo({ foo: "xxxxx", bar: "yyyyyy" })` won't work anymore, it _must_ be `foo({ foo: "bar", baz: "qux" })`. The same thing could be done for the ABI objects.

Alternatively, if we don't care about hardening the ABI like this then it might be good to make an ABI type.

**Comment by mcmire** [comment]
@gantunesr What do you think about this?

**Comment by gantunesr** [comment]
Excellent! Totally agree with you @mcmire, it's an easy change that can help avoid possible bugs in the future.

**Comment by mcmire** [comment]
I have a PR above to address this now :)
